# fly.toml app configuration file generated for weekly-email-summary on 2024-10-19T17:13:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weekly-email-summary'
primary_region = 'bos'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'weekly-email-summary.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

